# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate Unique Pairs Up To a Number
#'
#' This function generates all unique pairs of integers up to a given number.
#'
#' @param x An integer specifying the upper limit for pairs.
#' @param oneIndexed A logical indicating whether the pairs should be one
#' indexed. Default is TRUE.
#'
#' @return A list of unique pairs of integers up to the specified number.
#' @export
#' @keywords iteration
#' @examples
#' # Generate unique pairs up to 3 (one-indexed)
#' getUniquePairsUpTo(3)
#' # Generate unique pairs up to 3 (zero-indexed)
#' getUniquePairsUpTo(3, oneIndexed = FALSE)
getUniquePairsUpTo <- function(x, oneIndexed = TRUE) {
    .Call(`_FastUtils_getUniquePairsUpTo`, x, oneIndexed)
}

